sudo: required
services:
    - docker
before_install:
    - docker build -t thiagobolivar/docker-react -f Dockerfile.dev .

script:
    - docker run thiagobolivar/docker-react npm run test -- --coverage