sudo: required
services:
    - docker
before_install:
    - docker build -t thiagobolivar/docker-react -f Dockerfile.dev .

script:
    - docker run thiagobolivar/docker-react npm run test -- --coverage
deploy:
    provider: elasticbeanstalk
    region: "sa-east-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-sa-east-1-258413845430"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
